# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = "2"

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  
  config.vm.box = "ubuntu/bionic64"

  if Vagrant.has_plugin?("vagrant-librarian-puppet")
	config.librarian_puppet.puppetfile_dir = "../librarian"
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    	config.cache.scope = :box
  end

  ## memory
  config.vm.provider :virtualbox do |vb|
    	vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.define :web do |web_config|

    	web_config.vm.hostname = "web"
	web_config.vm.network :private_network, :ip => "192.168.33.10"

	web_config.vm.provider :aws do |aws|
      		aws.tags = { 'Name' => 'Web' }
    	end
	web_config.vm.provision "puppet" do |puppet|
		puppet.manifests_path = "../manifests"
		puppet.manifest_file = "wildfly.pp"
		web_config.vm.synced_folder "../deployments/", "/opt/wildfly/wildfly-13.0.0.Final/standalone/deployments/"
    	end
  end

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update -y
     apt-get install openjdk-8-jdk -y
     cd /tmp
     wget http://apt.puppet.com/puppetlabs-release-pc1-xenial.deb
     dpkg -i puppetlabs-release-pc1-xenial.deb
     apt-get -y install puppet-common
  SHELL

end
