# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = "2"

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  
  config.vm.box = "ubuntu/xenial64"

  if Vagrant.has_plugin?("vagrant-librarian-puppet")
    	config.librarian_puppet.puppetfile_dir = "librarian"
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    	config.cache.scope = :box
  end

  ## memory
  config.vm.provider :virtualbox do |vb|
    	vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  ## data of the aws
  config.vm.provider :aws do |aws, override|
        
        aws.elastic_ip = true

    	aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    	aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    	aws.keypair_name = ENV['AWS_KEYPAIR_NAME']

    	aws.ami = "ami-66506c1c"
	aws.region = "us-east-1"
	aws.instance_type = "t2.micro"
    	aws.subnet_id = ENV['AWS_SUBNET_ID']

	override.vm.box = "dummy"
  end

  ## 
  config.vm.define :web do |web_config|

    	web_config.vm.hostname = "web"
	web_config.vm.network :private_network, :ip => "192.168.33.10"

	web_config.vm.provider :aws do |aws|
      		aws.tags = { 'Name' => 'Web' }
    	end
	web_config.vm.provision "puppet" do |puppet|
     		puppet.manifest_file = "wildfly.pp"
		puppet.manifest_file = "tomcat.pp"
    	end
  end

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update -y
     apt-get install openjdk-8-jdk -y
     cd /tmp
     wget http://apt.puppet.com/puppetlabs-release-pc1-xenial.deb
     dpkg -i puppetlabs-release-pc1-xenial.deb
     apt-get -y install puppet-common
  SHELL

end
