# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = "2"

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/trusty64"

  if Vagrant.has_plugin?("vagrant-librarian-puppet")
  	config.librarian_puppet.puppetfile_dir = "librarian"
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    	config.cache.scope = :box
  end

  config.vm.provider :virtualbox do |vb|
    	vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provider :aws do |aws, override|
    	aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    	aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    	aws.keypair_name = ENV['AWS_KEYPAIR_NAME']

    	aws.ami = "ami-a18c8fc8"
    	aws.user_data = File.read("bootstrap.sh")
	aws.region = "us-east-1"
	aws.instance_type = "t2.micro"
    	aws.subnet_id = ENV['AWS_SUBNET_ID']

    	override.vm.box = "dummy"
    	override.ssh.username = "ubuntu"
    	override.ssh.private_key_path = ENV['AWS_PRIVATE_KEY_PATH']
  end

  config.vm.define :web do |web_config|
    	web_config.vm.hostname = "web"
    	web_config.vm.network :private_network, :ip => "192.168.33.10"
    
	web_config.vm.provider :aws do |aws|
      		aws.private_ip_address = "192.168.33.12"
      		aws.tags = { 'Name' => 'Web' }
    	end
    	
	web_config.vm.provision "puppet" do |puppet|
      		puppet.module_path = ["modules", "modules"]
      		puppet.manifest_file = "web.pp"
    	end
  end
end
