# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = "2"

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  
  config.vm.box = "ubuntu/bionic64"

  if Vagrant.has_plugin?("vagrant-librarian-puppet")
	config.librarian_puppet.puppetfile_dir = "../librarian"
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    	config.cache.scope = :box
  end

  ## memory
  config.vm.provider :virtualbox do |vb|
    	vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.define "java-demo" do |config|

      config.vm.provider :digital_ocean do |provider, override|
         override.ssh.private_key_path = '~/.ssh/id_rsa'
         override.vm.box = 'digital_ocean'
         override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
         override.nfs.functional = false
         provider.token = ENV['DG_TOKEN']
         provider.image = 'ubuntu-18-04-x64'
         provider.region = 'nyc1'
         provider.size = '1gb'

	 config.vm.provision "puppet" do |puppet|
                puppet.manifests_path = "../manifests"
                puppet.manifest_file = "wildfly.pp"
                config.vm.synced_folder "../deployments/", "/opt/wildfly/wildfly-13.0.0.Final/standalone/deployments/"
        end
     end

  end

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update -y
     apt-get install openjdk-8-jdk -y
     cd /tmp
     wget http://apt.puppet.com/puppetlabs-release-pc1-xenial.deb
     dpkg -i puppetlabs-release-pc1-xenial.deb
     apt-get -y install puppet-common
  SHELL

end
